import { faYoutube, faFacebook, faInstagram, faTwitter } from "@fortawesome/free-brands-svg-icons";
import {
  faHouseChimney,
  faClipboardUser,
  faMusic,
  faVideo,
  faPalette,
  faPaintBrush,
  faList,
  faChessQueen,
  // faRightFromBracket,
  faClapperboard,
  faCamera,
} from "@fortawesome/free-solid-svg-icons";

export const snsMenu = [
  {
    name: "페이스북",
    icon: faFacebook,
    type: "icon",
    root: "https://ko-kr.facebook.com/bravegirls.official/",
  },
  {
    name: "유튜브",
    icon: faYoutube,
    type: "icon",
    root: "https://www.youtube.com/channel/UCx_kYu6Wp1yxZP_KtrW52EQ",
  },
  {
    name: "인스타그램",
    icon: faInstagram,
    type: "icon",
    root: "https://www.instagram.com/bravegirls.official/",
  },
  {
    name: "트위터",
    icon: faTwitter,
    type: "icon",
    root: "https://twitter.com/BraveGirls",
  },
];

export const Menu = [
  {
    name: "홈",
    value: "HOME",
    type: "text",
    // root: Url.ROOT,
    root: "/",
    path: "/",
    children: [],
    icon: faHouseChimney,
    isLeaf: false,
  },
  {
    name: "멤버",
    value: "MEMBER",
    type: "text",
    root: "/member",
    path: "/member",
    children: [],
    icon: faClipboardUser,
    isLeaf: false,
  },
  {
    name: "앨범",
    value: "ALBUM",
    type: "text",
    root: "/album",
    path: "/album",
    children: [],
    icon: faMusic,
    isLeaf: false,
  },
  {
    name: "비디오",
    value: "VIDEO",
    type: "text",
    root: "/video",
    path: "/video",
    children: [
      {
        name: "뮤직비디오",
        type: "text",
        root: "/video/music",
        path: "/video/music",
        parent: "VIDEO",
        icon: faCamera,
        isLeaf: true,
      },
      {
        name: "퀸덤2",
        type: "text",
        root: "/video/queendom",
        path: "/video/queendom",
        parent: "VIDEO",
        icon: faChessQueen,
        isLeaf: true,
      },
      {
        name: "쁘클립",
        type: "text",
        root: "/video/bgclip",
        path: "/video/bgclip",
        parent: "VIDEO",
        icon: faClapperboard,
        isLeaf: true,
      },
    ],
    icon: faVideo,
    isLeaf: false,
  },
  {
    name: "캔버스",
    value: "CANVAS",
    type: "text",
    root: "/canvas",
    path: "/canvas",
    children: [
      {
        name: "그리기",
        value: "DRAW",
        type: "text",
        root: "/canvas/draw",
        path: "/canvas/draw",
        parent: "CANVAS",
        icon: faPaintBrush,
        isLeaf: true,
      },
      {
        name: "게시판",
        value: "BOARD",
        type: "text",
        root: "/canvas/board",
        path: "/canvas/board",
        parent: "CANVAS",
        icon: faList,
        isLeaf: true,
      },
    ],
    icon: faPalette,
  },
  // {
  //   name: "로그인",
  //   value: "LOGIN",
  //   type: "text",
  //   root: "/login",
  //   path: "/login",
  //   children: [],
  //   icon: faRightFromBracket,
  //   isLeaf: false,
  // },
];
